{{- if .Values.highAvailability.certManager.enabled }}
  {{- $domain:= (required "clusterName is required in chartValues when certManager is enabled" .Values.clusterName) }}
  {{- $domainWildcard := printf "*.%s" (required "clusterName is required in chartValues when certManager is enabled" .Values.clusterName) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: teleport-tls
  dnsNames:
  - {{ quote $domain }}
  - {{ quote $domainWildcard }}
  issuerRef:
    name: {{ required "highAvailability.certManager.issuerName is required in chart values" .Values.highAvailability.certManager.issuerName }}
    kind: {{ required "highAvailability.certManager.issuerKind is required in chart values" .Values.highAvailability.certManager.issuerKind }}
{{- end }}

{{- if or .Values.custom_tls.enabled .Values.custom_tls.generate_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: teleport-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.custom_tls.crt }}
  tls.key: {{ .Values.custom_tls.key }}
{{- end }}
